# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 13:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsPaper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=20)),
                ('totalVanzari', models.IntegerField()),
                ('hasCD', models.BooleanField(default=False)),
                ('hasBook', models.BooleanField(default=False)),
                ('priceWithoutAddons', models.IntegerField()),
                ('priceWithCD', models.IntegerField(blank=True, default=0, null=True)),
                ('priceWithBook', models.IntegerField(blank=True, default=0, null=True)),
                ('priceWithCDAndBook', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
    ]
